// Configure up to 50 questions here.
// Each question has:
// - text: the abstract or comment to show
// - isHuman: true if written by a human, false if generated by AI
// - type (optional): label such as "Thesis abstract", "Comment", etc.
const QUESTIONS = [
  {
    text: "This is a placeholder thesis abstract. Replace this text with a real or AI-generated abstract relevant to your study.",
    isHuman: true,
    type: "Thesis abstract",
  },
  {
    text: "In this comment, the author discusses the implications of large language models for academic writing and peer review processes.",
    isHuman: false,
    type: "Comment",
  },
  // Add up to 48 more questions here as needed.
];

if (QUESTIONS.length === 0) {
  console.warn("QUESTIONS array is empty. Add at least one question in script.js.");
}

const MAX_QUESTIONS = 50;
if (QUESTIONS.length > MAX_QUESTIONS) {
  console.warn(`QUESTIONS has ${QUESTIONS.length} items, but only the first ${MAX_QUESTIONS} will be used.`);
}

const effectiveQuestions = QUESTIONS.slice(0, MAX_QUESTIONS);

let currentIndex = 0;
let hasAnsweredCurrent = false;
let numCorrect = 0;
let numAnswered = 0;

const els = {
  questionLabel: document.getElementById("question-label"),
  questionTag: document.getElementById("question-tag"),
  questionText: document.getElementById("question-text"),
  progressText: document.getElementById("progress-text"),
  progressBarInner: document.getElementById("progress-bar-inner"),
  btnHuman: document.getElementById("btn-human"),
  btnAi: document.getElementById("btn-ai"),
  btnPrev: document.getElementById("btn-prev"),
  btnNext: document.getElementById("btn-next"),
  feedback: document.getElementById("feedback"),
  scoreCorrect: document.getElementById("score-correct"),
  scoreTotal: document.getElementById("score-total"),
};

const answers = new Array(effectiveQuestions.length).fill(null);

function clampIndex(index) {
  if (index < 0) return 0;
  if (index >= effectiveQuestions.length) return effectiveQuestions.length - 1;
  return index;
}

function renderQuestion() {
  const q = effectiveQuestions[currentIndex];
  const total = effectiveQuestions.length;
  const questionNumber = currentIndex + 1;

  els.questionLabel.textContent = `Question ${questionNumber}`;
  els.questionText.textContent = q.text;
  els.questionTag.textContent = q.type || "Item";

  els.progressText.textContent = `Question ${questionNumber} of ${total}`;
  const progressRatio = total > 0 ? questionNumber / total : 0;
  els.progressBarInner.style.width = `${Math.round(progressRatio * 100)}%`;

  els.btnPrev.disabled = currentIndex === 0;
  els.btnNext.disabled = !answers[currentIndex] && currentIndex !== total - 1;
  els.btnNext.textContent = currentIndex === total - 1 ? "Finish" : "Next ▶";

  resetChoiceStyles();
  applyAnswerStyles();
  renderFeedback();
  updateScoreSummary();
}

function resetChoiceStyles() {
  [els.btnHuman, els.btnAi].forEach((btn) => {
    btn.classList.remove("selected-correct", "selected-incorrect", "disabled");
  });
}

function applyAnswerStyles() {
  const q = effectiveQuestions[currentIndex];
  const answer = answers[currentIndex];

  if (!answer) return;

  const isCorrect = answer.choiceIsHuman === q.isHuman;
  const selectedButton = answer.choiceIsHuman ? els.btnHuman : els.btnAi;

  selectedButton.classList.add(isCorrect ? "selected-correct" : "selected-incorrect");
  [els.btnHuman, els.btnAi].forEach((btn) => btn.classList.add("disabled"));
}

function renderFeedback() {
  const q = effectiveQuestions[currentIndex];
  const answer = answers[currentIndex];

  els.feedback.textContent = "";
  els.feedback.classList.remove("correct", "incorrect");

  if (!answer) {
    return;
  }

  const isCorrect = answer.choiceIsHuman === q.isHuman;
  if (isCorrect) {
    els.feedback.textContent = "Correct! Your classification matches the ground truth.";
    els.feedback.classList.add("correct");
  } else {
    const actualLabel = q.isHuman ? "human-written" : "AI-generated";
    els.feedback.textContent = `Incorrect. This item was ${actualLabel}.`;
    els.feedback.classList.add("incorrect");
  }
}

function updateScoreSummary() {
  const totalAnswered = answers.filter(Boolean).length;
  const totalCorrect = answers.reduce((acc, a, idx) => {
    if (!a) return acc;
    return acc + (a.choiceIsHuman === effectiveQuestions[idx].isHuman ? 1 : 0);
  }, 0);

  numAnswered = totalAnswered;
  numCorrect = totalCorrect;

  els.scoreCorrect.textContent = numCorrect.toString();
  els.scoreTotal.textContent = numAnswered.toString();
}

function recordAnswer(choiceIsHuman) {
  const existing = answers[currentIndex];
  if (existing) {
    existing.choiceIsHuman = choiceIsHuman;
  } else {
    answers[currentIndex] = { choiceIsHuman };
  }
  hasAnsweredCurrent = true;
  renderQuestion();
}

function handleNext() {
  const lastIndex = effectiveQuestions.length - 1;

  if (currentIndex === lastIndex) {
    const percent =
      answers.length === 0
        ? 0
        : Math.round(
            (numCorrect / Math.max(1, answers.filter(Boolean).length)) * 100
          );

    alert(
      `Survey complete.\n\nYou answered ${numCorrect} out of ${numAnswered} answered items correctly (${percent}%).`
    );
    return;
  }

  currentIndex = clampIndex(currentIndex + 1);
  hasAnsweredCurrent = !!answers[currentIndex];
  renderQuestion();
}

function handlePrev() {
  currentIndex = clampIndex(currentIndex - 1);
  hasAnsweredCurrent = !!answers[currentIndex];
  renderQuestion();
}

function handleKeydown(event) {
  if (event.key === "ArrowLeft") {
    event.preventDefault();
    if (!els.btnPrev.disabled) handlePrev();
  } else if (event.key === "ArrowRight") {
    event.preventDefault();
    if (!els.btnNext.disabled) handleNext();
  } else if (event.key.toLowerCase() === "h") {
    event.preventDefault();
    if (!answers[currentIndex]) recordAnswer(true);
  } else if (event.key.toLowerCase() === "a") {
    event.preventDefault();
    if (!answers[currentIndex]) recordAnswer(false);
  }
}

function init() {
  if (!els.btnHuman || !els.btnAi) {
    console.error("Required DOM elements not found. Check index.html structure.");
    return;
  }

  els.btnHuman.addEventListener("click", () => {
    if (!answers[currentIndex]) {
      recordAnswer(true);
    }
  });

  els.btnAi.addEventListener("click", () => {
    if (!answers[currentIndex]) {
      recordAnswer(false);
    }
  });

  els.btnNext.addEventListener("click", handleNext);
  els.btnPrev.addEventListener("click", handlePrev);

  document.addEventListener("keydown", handleKeydown);

  renderQuestion();
}

window.addEventListener("DOMContentLoaded", init);

