"""
make_latex_tables.py

Emit booktabs LaTeX tables for the paper straight from the analysis output CSVs
(so the numbers can't drift from a hand-transcription). Writes everything to
csv_files/../latex_tables.txt. Requires \\usepackage{booktabs} in the preamble.

Covers: embedding detectability, NER distributions, per-condition linguistic
feature significance, and (if present) informal sentiment.

Run: python src/2_text_analysis_scripts/scripts/make_latex_tables.py
"""
import math
import os
from decimal import Decimal, ROUND_HALF_UP

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
_2TAS = os.path.dirname(HERE)
CSV = os.path.join(_2TAS, "csv_files")
OUT = os.path.join(_2TAS, "latex_tables.txt")

REPORTED = ["baseline", "human_like", "detector_evasive"]  # detector_aware excluded everywhere
COND_LABEL = {"baseline": "Baseline", "human_like": "Human-like",
              "detector_evasive": "Detector-evasive"}
TOP_N = 12


def tex_feat(f):
    return "\\texttt{" + f.replace("_", "\\_") + "}"


def tex_dir(d):
    if d == "llm > human":
        return "LLM $>$ H"
    if d == "human > llm":
        return "H $>$ LLM"
    return "$\\approx$"


def qfmt(q):
    q = float(q)
    if q <= 0:
        return "$<\\!10^{-300}$"
    if q >= 1e-3:
        return f"${q:.3g}$"
    e = math.floor(math.log10(q))
    m = q / 10 ** e
    return f"${m:.1f}\\times10^{{{e}}}$"


def num(x, nd=4):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def write_standalone(filename, tex, what):
    """Write one table to its own .tex next to the other standalone tables.

    Mirrors the header convention of judge_rationale_cues_by_register.tex: a
    GENERATED banner, the package requirements, and \\providecommand fallbacks for
    the shading macros so the file also compiles outside the thesis preamble. The
    \\providecommand's only fire if the preamble does NOT already define \\cg/\\crd,
    so a preamble definition always wins and the colour names guessed here are
    irrelevant in that case.
    """
    path = os.path.join(_2TAS, filename)
    header = f"""% GENERATED by src/2_text_analysis_scripts/scripts/make_latex_tables.py
% -- do not hand-edit. Re-run that script to refresh.
% Source of truth: csv_files/significance_tests_results.csv
% Contents: {what}
% REQUIRES: \\usepackage{{booktabs}}, \\usepackage[table]{{xcolor}}
\\providecommand{{\\cg}}[1]{{\\cellcolor{{hmgreen!#1}}}}
\\providecommand{{\\crd}}[1]{{\\cellcolor{{hmred!#1}}}}
% \\definecolor{{hmgreen}}{{HTML}}{{2E8B57}} % uncomment if used standalone
% \\definecolor{{hmred}}{{HTML}}{{C0392B}}   % uncomment if used standalone

"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + tex + "\n")
    return path


def read_twosample(dataset, cond):
    p = os.path.join(CSV, f"embedding_twosample_{dataset}_{cond}.csv")
    if not os.path.exists(p):
        return None
    d = dict(zip(*[pd.read_csv(p)[c] for c in ("metric", "value")]))
    return d


# ---------------------------------------------------------------------------
def table_embedding():
    rows = []
    for cond in REPORTED:
        f = read_twosample("formal", cond)
        i = read_twosample("informal", cond)
        if not f or not i:
            continue
        rows.append((COND_LABEL[cond],
                     num(f["classifier_cv_roc_auc"], 3), num(f["mean_pair_cosine"], 3),
                     num(i["classifier_cv_roc_auc"], 3), num(i["mean_pair_cosine"], 3)))
    body = "\n".join(f"    {r[0]:<26} & {r[1]} & {r[2]} & {r[3]} & {r[4]} \\\\" for r in rows)
    return f"""% ---- Embedding detectability ----
\\begin{{table}}[htbp]
  \\centering
  \\caption{{Human--LLM separability by prompt condition: cross-validated ROC AUC
  of a logistic-regression two-sample test on multilingual sentence embeddings
  (\\texttt{{paraphrase-multilingual-mpnet-base-v2}}, 5-fold CV, 1000 label
  permutations), and mean per-pair cosine similarity. AUC${{}}=0.5$ is chance;
  all conditions separate at permutation $p<0.001$.
  $n=170$ (formal) / $1{{,}}149$ (informal) pairs per class.}}
  \\label{{tab:embedding-detectability}}
  \\begin{{tabular}}{{lcccc}}
    \\toprule
    & \\multicolumn{{2}}{{c}}{{Formal}} & \\multicolumn{{2}}{{c}}{{Informal}} \\\\
    \\cmidrule(lr){{2-3}}\\cmidrule(lr){{4-5}}
    Condition & ROC AUC & Mean cos. & ROC AUC & Mean cos. \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}"""


# ---------------------------------------------------------------------------
# tab:features-gpt — the headline paired-difference table.
#
# Row order, labels and family grouping reproduce the hand-built Overleaf table
# so this generator is a drop-in replacement for it; generating it from the CSV
# is what stops the informal column drifting again when a corpus is corrected.
#
# NOTE on units: the Discourse-particles block reports two COUNT features while
# every other row is a rate. Counts are inflated by the informal length gap
# (LLM ~1,046 chars vs human ~269), e.g. booster_count d_z=+0.68 but
# booster_rate=+0.02. Swap in the commented rate variants below to normalise.
FEATURE_FAMILIES = [
    ("Sentence complexity", [
        ("Word count",                "n_alpha_tokens"),
        ("Sentence count",            "n_sentences"),
        ("Mean parse-tree depth",     "tree_depth_mean"),
        ("Mean dependency distance",  "dep_distance_mean"),
        ("Subordinate-clause rate",   "subordinate_clause_rate"),
    ]),
    ("Lexical diversity", [
        ("Lexical diversity (MATTR)", "mattr"),
        ("Lexical diversity (MTLD)",  "mtld"),
        ("Type-token ratio",          "ttr"),
        ("Bigram repetition rate",    "bigram_repetition_rate"),
        ("Function-word rate",        "function_word_rate"),
    ]),
    ("Pragmatic markers", [
        ("Hedge rate",                "hedge_rate"),
        ("Negation rate",             "negation_rate"),
    ]),
    ("Punctuation", [
        ("Comma rate",                "punct_comma"),
        ("Full-stop rate",            "punct_period"),
        ("Dash rate",                 "punct_dash"),
    ]),
    ("Discourse particles", [
        # hedge_informal_count DOES exist for formal (-0.13 ns / +0.34* / +0.41*),
        # but it is an informal-register construct and the Overleaf table has always
        # dashed it. INFORMAL_ONLY keeps that editorial choice explicit -- drop the
        # name from that set to print the formal figures instead.
        ("Informal-hedge count",      "hedge_informal_count"),
        # ("Informal-hedge rate",     "hedge_informal_rate"),
        ("Booster count",             "booster_count"),
        # ("Booster rate",            "booster_rate"),
        ("Discourse-particle rate",   "discourse_particle_rate"),
    ]),
    ("Named entity recognition", [
        ("Named-entity rate (all)",   "ner_total_rate"),
        ("\\quad location (LOC)",     "ner_LOC_rate"),
        ("\\quad person (PRS)",       "ner_PRS_rate"),
        ("\\quad organisation (ORG)", "ner_ORG_rate"),
    ]),
    ("Sentiment analysis", [
        # Informal-register only: formal abstracts are near-uniformly neutral
        # (register floor effect), so the formal columns print as em-dashes.
        ("Signed polarity",           "signed_polarity"),
        ("Affective extremity",       "affective_extremity"),
        ("Subjective rate",           "is_subjective"),
    ]),
]

SHADE_SCALE = 25  # cell shading = round(|d_z| * SHADE_SCALE), as in the contrast table

# Features suppressed in the formal columns as an editorial choice, even though the
# CSV has values for them (see the Discourse-particles note above).
INFORMAL_ONLY = {"hedge_informal_count", "hedge_informal_rate"}


def table_features_gpt(sig):
    """The main paired-difference table: feature x (register x condition), shaded.

    Cells are \\cg{}/\\crd{}-shaded d_z with a significance star; features absent
    for a register (informal-only pragmatics) print as an em-dash.
    """
    def cell(dataset, cond, feat):
        if dataset == "formal" and feat in INFORMAL_ONLY:
            return "---"
        r = sig[(sig.dataset == dataset) & (sig.condition == cond)
                & (sig.feature == feat)]
        if r.empty:
            return "---"
        r = r.iloc[0]
        dz = round(float(r["cohens_dz"]), 2)
        mac = "cg" if dz > 0 else "crd"
        shade = int(Decimal(abs(dz) * SHADE_SCALE).quantize(Decimal("1"),
                                                           rounding=ROUND_HALF_UP))
        star = "*" if bool(r["significant_fdr_0.05"]) else ""
        return f"\\{mac}{{{shade}}}${dz:+.2f}${star}"

    lines = []
    for family, rows in FEATURE_FAMILIES:
        if lines:
            lines.append("    \\addlinespace[4pt]")
        lines.append(f"    \\multicolumn{{7}}{{l}}{{\\textit{{{family}}}}} \\\\")
        lines.append("    \\addlinespace[2pt]")
        for label, feat in rows:
            cells = [cell(ds, c, feat)
                     for ds in ("formal", "informal") for c in REPORTED]
            lines.append(f"    {label:<28} & " + " & ".join(cells) + " \\\\")
    body = "\n".join(lines)

    def npairs(dataset, feat="n_alpha_tokens"):
        r = sig[(sig.dataset == dataset) & (sig.condition == "baseline")
                & (sig.feature == feat)]
        return None if r.empty else int(r.iloc[0]["n_pairs"])

    def texnum(n):
        """1149 -> '1{,}149' so the thousands comma keeps its spacing in math mode."""
        return f"{n:,}".replace(",", "{,}")

    n_f, n_i = npairs("formal"), npairs("informal")
    n_mtld = npairs("informal", "mtld")
    mtld_note = (f" (informal MTLD: $n={n_mtld}$, MTLD is undefined for the "
                 f"shortest comments)" if n_mtld and n_mtld != n_i else "")

    # how uninformative the star is in the informal columns
    inf = sig[(sig.dataset == "informal") & (sig.condition == "baseline")]
    n_sig = int(inf["significant_fdr_0.05"].sum())

    return f"""% ---- Main paired-difference table (tab:features-gpt) ----
% REQUIRES: booktabs + the \\cg / \\crd shading macros from the preamble.
% NOTE: the caption cites Appendix~\\ref{{app:full-features}} -- define that label
% on the appendix holding the full feature set, or the reference prints as "??".
\\begin{{table}}[htbp]
  \\centering
  \\small
  \\begin{{tabular}}{{lcccccc}}
    \\toprule
    & \\multicolumn{{3}}{{c}}{{Formal}} & \\multicolumn{{3}}{{c}}{{Informal}} \\\\
    \\cmidrule(lr){{2-4}}\\cmidrule(lr){{5-7}}
    Feature & Base & Hum-like & Det-evasive & Base & Hum-like & Det-evasive \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
  \\caption{{Paired differences between human-written and GPT-5.2--generated
  Swedish text (Cohen's $d_z$, LLM $-$ human; paired Wilcoxon signed-rank with
  Benjamini--Hochberg FDR correction). Positive (green) values indicate higher
  feature values in LLM text; negative (red) values indicate higher values in
  human text; shading intensity is proportional to $|d_z|$. * denotes
  significance at $q<0.05$. A representative subset of the full feature set is
  shown, selecting one feature per redundant construct family; full results in
  Appendix~\\ref{{app:full-features}}. An em-dash marks a feature not reported
  for that register. Formal: $n={n_f}$ pairs; informal: $n={texnum(n_i)}$
  pairs{mtld_note}. Note that at informal $n$ the star is close to uninformative
  --- {n_sig} of {len(inf)} features clear $q<0.05$ at baseline --- so the effect
  size, not the star, is what distinguishes these rows.}}
  \\label{{tab:features-gpt}}
\\end{{table}}"""


GROUP_LABEL = {
    "syntactic_complexity": "Syntactic complexity",
    "stylometric_surface": "Stylometric surface",
    "pragmatic_markers": "Pragmatic markers",
    "ner": "Named entity recognition",
}
GROUP_ORDER = ["stylometric_surface", "pragmatic_markers", "syntactic_complexity", "ner"]


def table_features_full(sig, dataset, conds=REPORTED):
    """The FULL feature set for one register -- the appendix table that
    tab:features-gpt's caption promises via \\ref{app:full-features}.

    Unlike table_features_gpt this selects nothing: every feature present in
    significance_tests_results.csv for `dataset` is printed, grouped by
    feature_group and ordered by |d_z| at baseline within each group. Features are
    named by their raw column name (\\texttt{}), not a prose label, so a reader can
    map every row back to the CSV without a lookup table.

    conds defaults to REPORTED, i.e. detector_aware is excluded, matching every
    other table in the document. Pass conds=REPORTED + ["detector_aware"] to include
    it -- the numbers exist in the CSV either way.
    """
    sub = sig[sig.dataset == dataset]
    if sub.empty:
        return None

    def cell(cond, feat):
        r = sub[(sub.condition == cond) & (sub.feature == feat)]
        if r.empty:
            return "---"
        r = r.iloc[0]
        dz = round(float(r["cohens_dz"]), 2)
        mac = "cg" if dz > 0 else "crd"
        shade = int(Decimal(abs(dz) * SHADE_SCALE).quantize(Decimal("1"),
                                                           rounding=ROUND_HALF_UP))
        star = "*" if bool(r["significant_fdr_0.05"]) else ""
        return f"\\{mac}{{{shade}}}${dz:+.2f}${star}"

    base = sub[sub.condition == "baseline"].copy()
    ncol = 3 + len(conds)
    lines = []
    for grp in GROUP_ORDER + [g for g in base["feature_group"].unique()
                              if g not in GROUP_ORDER]:
        rows = base[base.feature_group == grp]
        if rows.empty:
            continue
        rows = rows.reindex(rows["cohens_dz"].abs().sort_values(ascending=False).index)
        if lines:
            lines.append("    \\addlinespace[4pt]")
        grp_label = GROUP_LABEL.get(grp, grp.replace("_", " ").capitalize())
        lines.append(f"    \\multicolumn{{{ncol}}}{{l}}{{\\textit{{{grp_label}}} "
                     f"({len(rows)})}} \\\\")
        lines.append("    \\addlinespace[2pt]")
        for _, r in rows.iterrows():
            cells = [cell(c, r["feature"]) for c in conds]
            lines.append(f"    {tex_feat(r['feature']):<44} & "
                         f"{num(r['median_human'], 3)} & {num(r['median_llm'], 3)} & "
                         + " & ".join(cells) + " \\\\")
    body = "\n".join(lines)

    n_main = int(base["n_pairs"].mode().iloc[0])
    odd = base[base["n_pairs"] != n_main][["feature", "n_pairs"]]
    n_note = ""
    if not odd.empty:
        bits = "; ".join(f"\\texttt{{{f.replace('_', chr(92) + '_')}}} $n={int(n)}$"
                         for f, n in odd.itertuples(index=False))
        n_note = (f" All features have $n={n_main:,}$".replace(",", "{,}")
                  + f" pairs except {bits}, which is undefined for the shortest texts.")

    nsig = {c: int(sub[(sub.condition == c)]["significant_fdr_0.05"].sum())
            for c in conds}
    sig_note = ", ".join(f"{COND_LABEL[c]} {nsig[c]}/{len(base)}" for c in conds)

    header = " & ".join(f"{COND_LABEL[c]}" for c in conds)
    excluded = [c for c in sig["condition"].unique() if c not in conds]
    excl_note = (f"\n% NOTE: condition(s) {excluded} present in the CSV but omitted here"
                 f" (house convention); pass conds= to include them." if excluded else "")
    caveat = ""
    if os.path.exists(os.path.join(CSV, "informal_normalization_delta.csv")) and dataset == "informal":
        caveat = ("\n% CAVEAT: punct_semicolon's human values are 76% scrape artefact (the `;`"
                  "\n% inside an unescaped &gt;). See informal_normalization_delta.csv -- the"
                  "\n% normalized d_z are -0.04/-0.07/-0.08; significance is unchanged.")

    label = "app:full-features" + ("" if dataset == "informal" else "-" + dataset)
    pointed_at = ("\n% tab:features-gpt's caption points \\ref{app:full-features} here, so that"
                  "\n% label must not move unless you also update the caption (or put the label"
                  "\n% on the appendix SECTION and let it cover both registers)."
                  if dataset == "informal" else "")
    return f"""% ---- FULL feature set, {dataset} register ({label}) ----
% REQUIRES: booktabs + the \\cg / \\crd shading macros from the preamble.
% {len(base)} features x {len(conds)} conditions.{pointed_at}
% If it overflows the page, wrap in longtable or switch to table*.{excl_note}{caveat}
\\begin{{table}}[htbp]
  \\centering
  \\footnotesize
  \\setlength{{\\tabcolsep}}{{4pt}}
  \\begin{{tabular}}{{l rr {'c' * len(conds)}}}
    \\toprule
    & \\multicolumn{{2}}{{c}}{{Median}} & \\multicolumn{{{len(conds)}}}{{c}}{{Cohen's $d_z$}} \\\\
    \\cmidrule(lr){{2-3}}\\cmidrule(l){{4-{3 + len(conds)}}}
    Feature & H & LLM & {header} \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
  \\caption{{Complete {dataset} feature set: paired differences between
  human-written and GPT-5.2--generated Swedish (Cohen's $d_z$, LLM $-$ human;
  paired Wilcoxon signed-rank, Benjamini--Hochberg FDR within each condition's
  family of {len(base)} features). Positive (green) values indicate higher feature
  values in LLM text, negative (red) higher in human text; shading is proportional
  to $|d_z|$. * denotes $q<0.05$. Medians are from the baseline condition.
  Features are grouped by extractor and ordered by $|d_z|$ at baseline; names are
  the raw column names in
  \\texttt{{significance\\_tests\\_results.csv}}.{n_note} Significant features per
  condition: {sig_note} --- at this $n$ the star is close to uninformative, so
  $|d_z|$ is what distinguishes rows. Note that \\texttt{{\\_count}} features scale
  with length and \\texttt{{\\_rate}} features do not, so the two disagree by
  construction wherever the LLM writes longer text.}}
  \\label{{{label}}}
\\end{{table}}"""


def table_feature_detector(cv="grouped"):
    """Feature-based (non-LLM) detector: CV ROC AUC / accuracy / F1 per condition.

    Reports the `cv` scheme as the headline (grouped = StratifiedGroupKFold, which
    keeps every comment of a thread in one fold, so it cannot be inflated by topic
    leakage); the stratified figures go in the caption for comparison.
    """
    p = os.path.join(CSV, "feature_detector_results.csv")
    if not os.path.exists(p):
        return None
    df = pd.read_csv(p)
    df = df[df.cv == cv]
    if df.empty:
        return None

    def cell(dataset, cond):
        r = df[(df.dataset == dataset) & (df.condition == cond)]
        if r.empty:
            return None
        r = r.iloc[0]
        return (f"{num(r['roc_auc'])} & {num(r['roc_auc_sd'])} & "
                f"{num(r['accuracy'], 3)} & {num(r['f1'], 3)}")

    lines = []
    for cond in REPORTED:
        f, i = cell("formal", cond), cell("informal", cond)
        if not f or not i:
            continue
        lines.append(f"    {COND_LABEL[cond]:<18} & {f} & {i} \\\\")
    if not lines:
        return None
    body = "\n".join(lines)

    # n per class and feature count are constant within a dataset
    nf = df[df.dataset == "formal"].iloc[0]
    ni = df[df.dataset == "informal"].iloc[0]

    def auc(dataset, cond):
        return float(df[(df.dataset == dataset) & (df.condition == cond)].iloc[0]["roc_auc"])

    def fmt_delta(dataset):
        """'0.9755 $\\to$ 0.9928' — baseline vs detector_evasive AUC for a register."""
        return (f"{num(auc(dataset, 'baseline'))} $\\to$ "
                f"{num(auc(dataset, 'detector_evasive'))}")

    # stratified counterpart, quoted in the caption so both schemes are on record
    alt = pd.read_csv(p)
    alt = alt[alt.cv == "stratified"]
    alt_txt = "; ".join(
        f"{COND_LABEL[c]} "
        f"{num(alt[(alt.dataset=='formal') & (alt.condition==c)].iloc[0]['roc_auc'])}/"
        f"{num(alt[(alt.dataset=='informal') & (alt.condition==c)].iloc[0]['roc_auc'])}"
        for c in REPORTED
        if not alt[(alt.dataset == 'formal') & (alt.condition == c)].empty
        and not alt[(alt.dataset == 'informal') & (alt.condition == c)].empty)

    return f"""% ---- Feature-based detector ----
\\begin{{table}}[htbp]
  \\centering
  \\caption{{Feature-based (non-LLM) detector: a balanced logistic regression
  trained on the handcrafted linguistic features alone
  ({int(nf['n_features'])} formal / {int(ni['n_features'])} informal features from syntactic complexity,
  stylometric surface, pragmatic markers and NER), scored by 5-fold
  cross-validation. Folds are grouped so that both halves of a pair --- and, in
  the informal register, every comment from the same thread --- stay in one
  fold, so the scores cannot be inflated by topic leakage.
  AUC${{}}=0.5$ is chance; every cell separates at $p<0.001$ (1000 label
  permutations). $n={int(nf['n_per_class'])}$ formal / $n={int(ni['n_per_class'])}$ informal documents per class
  (informal drops {1149 - int(ni['n_per_class'])} of the 1{{,}}149 pairs for missing feature values).
  Stratified (ungrouped) CV gives near-identical AUCs, formal/informal:
  {alt_txt}.
  Contrast with Table~\\ref{{tab:embedding-detectability}}: the interpretable
  feature detector separates human from LLM text better than the embedding
  two-sample test in every condition and both registers. Prompt-based evasion
  does not defeat it --- in the informal register the detector-evasive prompt
  makes text \\emph{{more}} detectable ({fmt_delta('informal')}), and in the
  formal register it barely dents an already near-ceiling score
  ({fmt_delta('formal')}).}}
  \\label{{tab:feature-detector}}
  \\begin{{tabular}}{{lcccccccc}}
    \\toprule
    & \\multicolumn{{4}}{{c}}{{Formal}} & \\multicolumn{{4}}{{c}}{{Informal}} \\\\
    \\cmidrule(lr){{2-5}}\\cmidrule(lr){{6-9}}
    Condition & ROC AUC & SD & Acc. & $F_1$ & ROC AUC & SD & Acc. & $F_1$ \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}"""


def table_ner(dataset, label):
    p = os.path.join(CSV, f"ner_distribution_{dataset}.csv")
    if not os.path.exists(p):
        return None
    df = pd.read_csv(p, index_col=0)
    heads = {"Human": "Human", "LLM baseline": "Baseline", "LLM human-like": "Human-like",
             "LLM detector-evasive": "Det-evasive"}
    cols = [c for c in heads if c in df.columns]
    header = " & ".join(["Entity"] + [heads[c] for c in cols])
    lines = []
    for ent, row in df.iterrows():
        lines.append(f"    {ent:<22} & " + " & ".join(num(row[c], 3) for c in cols) + " \\\\")
    body = "\n".join(lines)
    colspec = "l" + "c" * len(cols)
    return f"""% ---- NER {dataset} ----
\\begin{{table}}[htbp]
  \\centering
  \\caption{{Named-entity rate (mean entities per 100 content tokens),
  {label} register, by source. Swedish SUC tagset (\\texttt{{sv\\_core\\_news\\_lg}}).}}
  \\label{{tab:ner-{dataset}}}
  \\begin{{tabular}}{{{colspec}}}
    \\toprule
    {header} \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}"""


def table_significance(sig, dataset, cond):
    sub = sig[(sig.dataset == dataset) & (sig.condition == cond) & (sig["significant_fdr_0.05"])].copy()
    if sub.empty:
        return None
    sub["absdz"] = sub["cohens_dz"].abs()
    sub = sub.sort_values("absdz", ascending=False).head(TOP_N)
    lines = []
    for _, r in sub.iterrows():
        dz = f"{r['cohens_dz']:+.2f}"
        lines.append(f"    {tex_feat(r['feature']):<40} & {num(r['median_human'])} & "
                     f"{num(r['median_llm'])} & {dz} & {tex_dir(r['direction'])} & {qfmt(r['p_fdr_bh'])} \\\\")
    body = "\n".join(lines)
    ntot = len(sig[(sig.dataset == dataset) & (sig.condition == cond)])
    nsig = len(sig[(sig.dataset == dataset) & (sig.condition == cond) & (sig["significant_fdr_0.05"])])
    cond_label = COND_LABEL[cond].replace("$^{\\dagger}$", "")  # extracted: f-string exprs can't hold a backslash on py<3.12
    return f"""% ---- Significance: {dataset} / {cond} ----
\\begin{{table}}[htbp]
  \\centering
  \\caption{{{dataset.capitalize()} register, {cond_label} condition:
  top {min(TOP_N,len(sub))} features by $|d_z|$ (paired Wilcoxon signed-rank).
  $d_z>0$ means LLM $>$ human. {nsig} of {ntot} features significant at BH-FDR $q<0.05$.
  $n$={'170' if dataset=='formal' else '1{,}149'} pairs.}}
  \\label{{tab:sig-{dataset}-{cond}}}
  \\begin{{tabular}}{{lccccc}}
    \\toprule
    Feature & Med.\\,H & Med.\\,LLM & $d_z$ & Dir. & $q$ \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}"""


def table_sentiment():
    p = os.path.join(CSV, "inf_sentiment_distribution_by_condition.csv")
    if not os.path.exists(p):
        return None
    df = pd.read_csv(p)
    df = df[~df["group"].str.contains("detector_aware")]  # not in reported set
    lines = []
    for _, r in df.iterrows():
        lines.append(f"    {r['group']:<20} & {int(r['n'])} & {r['POSITIVE_proportion']*100:.1f} & "
                     f"{r['NEUTRAL_proportion']*100:.1f} & {r['NEGATIVE_proportion']*100:.1f} & "
                     f"{r['median_signed_polarity']:+.3f} & {r['subjective_rate']*100:.1f} \\\\")
    body = "\n".join(lines)
    return f"""% ---- Informal sentiment ----
\\begin{{table}}[htbp]
  \\centering
  \\caption{{Sentiment-label mix (\\%), median signed polarity ($p_{{pos}}-p_{{neg}}$)
  and subjectivity rate for the informal register, by source
  (\\texttt{{KBLab/robust-swedish-sentiment-multiclass}}).}}
  \\label{{tab:sentiment-informal}}
  \\begin{{tabular}}{{lrrrrrr}}
    \\toprule
    Source & $n$ & POS & NEU & NEG & Med.\\,pol. & Subj.\\,\\% \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}"""


def main():
    parts = ["% =====================================================================",
             "% LaTeX tables for the CLUU thesis results. Requires \\usepackage{booktabs}.",
             "% Generated by make_latex_tables.py from the analysis output CSVs.",
             "% =====================================================================", ""]

    sig = pd.read_csv(os.path.join(CSV, "significance_tests_results.csv"))
    parts.append(table_features_gpt(sig))

    # the appendix table tab:features-gpt's caption references. Also written to its
    # own .tex per register, since that is how the other appendix-sized tables ship.
    standalone = []
    for ds in ("informal", "formal"):
        t = table_features_full(sig, ds)
        if t:
            parts.append("\n" + t)
            nfeat = len(sig[(sig.dataset == ds) & (sig.condition == "baseline")])
            standalone.append(write_standalone(
                f"full_feature_table_{ds}.tex", t,
                f"complete {ds} feature set ({nfeat} features x {len(REPORTED)} "
                f"conditions), paired human-vs-GPT-5.2 Cohen's d_z"))

    parts.append("\n" + table_embedding())

    fd = table_feature_detector()
    if fd:
        parts.append("\n" + fd)

    for ds, lab in (("formal", "formal"), ("informal", "informal")):
        t = table_ner(ds, lab)
        if t:
            parts.append("\n" + t)

    for ds in ("formal", "informal"):
        for cond in REPORTED:
            t = table_significance(sig, ds, cond)
            if t:
                parts.append("\n" + t)

    st = table_sentiment()
    if st:
        parts.append("\n" + st)
    else:
        parts.append("\n% [sentiment table pending — inf_sentiment_distribution_by_condition.csv "
                     "not yet written; re-run this script once affective_analysis.py finishes]")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")
    print(f"wrote {OUT}")
    for p in standalone:
        print(f"wrote {p}")
    print(f"  tables: features-gpt, full-features (informal+formal), embedding, "
          f"feature detector{'' if fd else ' (SKIPPED)'}, "
          f"NER (formal+informal), significance "
          f"({len(REPORTED)} conds x 2 datasets), sentiment={'yes' if st else 'PENDING'}")


if __name__ == "__main__":
    main()
