// Configure up to 50 questions here.
// Each question has:
// - text: the abstract or comment to show
// - isHuman: true if written by a human, false if generated by AI
// - type (optional): label such as "Thesis abstract", "Comment", etc.
const QUESTIONS = [
  // === HUMAN-GENERATED ABSTRACTS (10) ===
  {
    text: "Syftet med denna uppsats är att belysa hur visionen om det narkotikafria samhället uppenbarar sig i diskurser som behandlar narkotikamissbruk som socialt problem. Empiriskt material i form av ett policydokument och en debattföljetong har analyserats utifrån ett socialkonstruktivistiskt och diskursanalytiskt perspektiv. Analysen pekar mot att definitionskampen om narkotikamissbruk som socialt problem finns över många diskurser; samtidigt ses visionen om det narkotikafria samhället ofta vara närvarande. En nationell diskurs som kan ses utgå från vad vi som nation anser och vill ha i vårt land. En moraldiskurs som lägger värde i olika beteenden och åsikter. En juridisk och polisiär diskurs som utifrån narkotikas juridiska status ramar in fenomenet och en barn-och ungdomsdiskurs som formulerar narkotikan som det största hotet. Alla dessa kan enligt studien ses som en del i konstruktionen av narkotikamissbruk som socialt problem.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Arbetsmarknadens förändringar i form av högre arbetstakt, tillfälliga anställningar och krav på flexibla arbetsvillkor, gör att allt fler upplever stress i arbetslivet. Långvarig stress medför stora hälsorisker för individen. Eftersom många av dagens sjukskrivningar beror på stressrelaterade sjukdomar, såsom depression och utmattning är det viktigt att studera metoder för stresshantering på arbetsplatsen. Beröring i form av massage kan minska stress hos individer samt fungerar som ett komplement i behandlingen för stressrelaterade sjukdomar. Ett fältexperiment med 28 tjänstemän utfördes för att undersöka om en kortvarig massage på arbetstid kunde inverka positivt på den arbetsrelaterade stressen jämfört med en avslappningsövning och vanlig rast. Studien visade signifikant minskning av stressnivån efter massageinterventionen. Resultatet ger en antydan om att upplevelsen av stress går att reducera med hjälp av fysisk beröring. Stickprovets storlek samt förväntnings-effektens inverkan på resultatet diskuteras.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Syftet med studien är att få en fördjupad förståelse för hur pedagoger tolkar och utvecklar arbetet kring begreppet hållbar utveckling utifrån den kunskap de besitter. Teorier om kunskap och hållbar utveckling samt begreppet handlingskompetens är centrala delar i föreliggande studie. Studien utgår från en kvalitativ metod och är grundad på semistrukturerade intervjuer med sammanlagt sex pedagoger från två förskolor i södra Sverige. Studien utgår från två forskningsfrågor: (1) hur förhåller sig pedagoger till begreppet hållbar utveckling ur ett lärandeperspektiv samt (2) om normer och värderingar synliggörs, hur speglas dessa i pedagogernas arbete med kunskapsbildning för hållbar utveckling. Resultatet av studien visar att pedagogers uppfattningar av begreppet hållbar utveckling riktar sig åt de tre dimensionerna ekologisk, ekonomisk och social. Pedagogernas kunskapsbildning grundar sig i fortbildningen Grön flagg eller pedagogernas eget intresse. Främst sker lärandet för hållbar utveckling utifrån ämnen som kan göras konkreta för barnen, till exempel källsortering och skräpplockning.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "I detta arbete har jag tittat på handledning på arbetsplatser. Handledning är idag ett svårdefinierbart begrepp som används allt mer på arbetsplatser. Syftet med detta arbete är att studera handledning och olika handledningsprocesser och se hur man skulle kunna använda sig av dem på arbetsplatser och i medarbetarsamtalet. Jag kommer att avgränsa mig genom att titta på momentet som rör medarbetarens utveckling i medarbetarsamtalet. I min teoretiska utgångspunkt har jag utgått ifrån att det kan förekomma handledning i medarbetarsamtalet, men att man inte kan se hela samtalet som handledning. För att undersöka detta har jag intervjuat 8 personer, fördelat på 2 arbetsplatser, om medarbetarsamtalet. Hälften har varit chefer och hälften medarbetare. I intervjuerna har det framkommit att man definitivt kan se handledande förhållningssätt i medarbetarsamtalet på båda företagen och att man också kan använda sig av de metoder och tankesätt som finns inom handledning för att utveckla medarbetarsamtalet ytterligare.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "I Samkönade äktenskaps vara eller icke vara inom Svenska kyrkan utförs en argumentationsanalys, baserad på hermeneutiks metod och kvalitativ textanalys, av debattartiklar som behandlat frågan som Svenska kyrkan ska behålla vigselrätten efter att svenska staten har gjort äktenskapsbalken könsneutral. Alla undersökta debattartiklar är publicerade mellan 2008-12-11 och 2009-10-31 i Kyrkans tidning och Dagens Nyheter. I resultatanalysen framgår det att både ja- och nej-sidan använder sig av ungefär samma typer av argument men med olika vinklingar och tolkningar. Nej-sidan använder sig dock mer av ett toleransperspektiv än ja-sidan. I ja-sidans argumenterande kan man hitta en underliggande normkritik av heteronormativiteten.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "I uppsatsen kopplas styrdokumentens uppmaning om undervisning kring intersektionalitet med det innehåll som finns i religionskunskapsläroböcker för gymnasiet som publicerats efter gymnasiereformen 2011. Syftet var att studera om läroböckerna tar upp intersektionalitet uttalat eller indirekt och/eller om de olika kategorierna kön, sexualitet, socioekonomisk bakgrund och etnicitet behandlas var för sig samt i vilka sammanhang det i sådana fall sker. Tre frågeställningar formulerades. Den första handlade om hur gymnasiets religionsläroböcker med utgivning från och med 2011 beskriver förhållandet mellan världsreligionerna och kategorierna kön, sexualitet, socioekonomisk bakgrund och etnicitet. Den andra frågan handlade om i vilka andra sammanhang (kapitel) de olika kategorierna beskrivs i läroböckerna. Den tredje frågan gällde vad som tas upp om själva begreppet samt fenomenet intersektionalitet i dessa religionsläroböcker.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Denna uppsats behandlar Paulus syn på lagen vilket är ett mycket omdebatterat område inom paulusforskningen. Frågan om Paulus lagsyn är så central för den övergripande paulustolkingen att alla som vill förstå Paulus och hans texter måste bilda sig en uppfattning om detta. Det har skrivits många hyllmeter och diskussionen verkar långt ifrån avslutad. Frågan kräver dock tydliga avgränsningar för att kunna behandlas i denna relativt korta uppsats. Därför kommer jag fokusera på en perikop i ett av Paulus brev som behandlar denna fråga. Min frågeställning blir då: Vad menar Paulus med 'lagen' i Rom 3:21-31?",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Ämnet för denna undersökning är de teologiska perspektiven runt två gudomligförklarade kungar i det forntida Mesopotamien, nämligen den gammalakkadiske kungen Naram-Sin (ca. 2254-2218 f.kr.) och den nysumeriske kungen Shulgi (ca. 2094-2047 f.kr.). De teologiska perspektiven behandlas här med hjälp av en induktionsbaserad historisk undersökning som utgår från vad olika forskare har skrivit i ämnet. Eftersom detta är en c-uppsats och det inte har varit möjligt att använda sig av primärkällor såsom arkeologiskt material och historiska källor på originalspråk så utgår denna undersökning uteslutande från forskningslitteratur. Undersökningen består av tre delar; i de två första delarna behandlas de teologiska perspektiven på kungarna var för sig och i det tredje görs en jämförelse mellan perspektiven. I undersökningen framkommer det att perspektiven är ganska spretiga och går i många olika riktningar och även att det finns skillnader och likheter i perspektiven mellan kungarna. Två teman som dock ofta återkommer är fruktbarhet och himlen.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Denna studie syftar till att undersöka vad blivande lärare och aktiva lärare har för attityder till skolavslutning och högtidsfirande i kyrkan samt skolavslutning och högtidsfirande i kyrkan med konfessionella inslag. Studien baseras på en internetenkät som blivande lärare och aktiva lärare svarat på. Resultatet visar att den största andelen av de aktiva lärarna och blivande lärarna var positiva till vistelsen i kyrkolokalerna i samband med skolavslutningar och högtidsfirande. Den största andelen var däremot negativa till företeelsen med konfessionella inslag vid dessa högtidsfiranden. Äldre aktiva lärare och blivande lärare var i högre grad positiva till både vistelsen i kyrkan och de konfessionella inslagen än de yngre. Slutsatserna är att sekulariseringen i Sverige ser ut att fortsätta i linje med de reviderade sekulariseringsteorierna, då konfessionalitet inte längre ses som något önskvärt bland den största andelen av aktiva lärare och blivande lärare.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "En stor del av Sveriges bebyggelse har byggts mellan 1965 och 1974 eftersom det rådde stor bostadsbrist i Sverige. Regeringen beslutade att en miljon bostäder skulle uppföras under denna tid, det s.k. miljonprogrammet. Det byggdes bostäder i varierande former och storlekar för att bygga bort bostadsbristen. Storskaligheten och en stor grad av upprepning av identiska hus är kännetecken för miljonprogrammets bebyggelser. Nu är det dags att renovera dessa byggnader. I och med att dessa byggnader är av allmänt intresse då de speglar en del av Sveriges arkitekturhistoria ställer kommunerna vissa krav vid renovering av dem. Det kommunala företaget Gavlegårdarna i Gävle tar initiativ till att utveckla bygglovsprocessen för sådana bebyggelser. Detta görs för att reducera tiden för framställande av ett godkänt bygglov samt effektivisera och underlätta kommunikationen med kommunen under hela projektet.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  // === AI-GENERATED ABSTRACTS (10) ===
  {
    text: "Denna uppsats syftar till att undersöka hur föreställningen om ett narkotikafritt samhälle tar form i diskurser där narkotikamissbruk förstås som ett socialt problem. Som empiri används ett policydokument och en debattserie, vilka analyseras med ett socialkonstruktivistiskt och diskursanalytiskt angreppssätt. Resultaten visar att kampen om hur narkotikamissbruk ska definieras förs inom flera parallella diskurser, där visionen om det narkotikafria samhället återkommer som en genomgående utgångspunkt. Studien identifierar en nationell diskurs som tar avstamp i idéer om vad 'vi' som land bör stå för, en moraldiskurs som värderar handlingar och hållningar, samt en juridisk/polisiär diskurs som med lagstiftningens ramar avgränsar fenomenet. Därtill framträder en barn- och ungdomsdiskurs som beskriver narkotika som ett särskilt allvarligt hot. Sammantaget bidrar dessa diskurser till att konstruera narkotikamissbruk som ett socialt problem.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Förändringar på arbetsmarknaden, såsom ökat tempo, otrygga anställningar och krav på flexibilitet, gör att fler upplever stress i arbetet. Långvarig stress innebär betydande hälsorisker för individen. Då en stor del av dagens sjukskrivningar kopplas till stressrelaterade tillstånd, exempelvis depression och utmattningssyndrom, är det angeläget att undersöka effektiva insatser för stresshantering på arbetsplatsen. Beröring, i synnerhet massage, har visats kunna sänka stressnivåer och kan även utgöra ett komplement vid behandling av stressrelaterad ohälsa. I ett fältexperiment med 28 tjänstemän prövades om en kort massage under arbetstid kunde minska arbetsrelaterad stress jämfört med en avslappningsövning och en ordinarie rast. Resultaten visade en signifikant stressreduktion efter massageinsatsen. Fynden tyder på att upplevd stress kan dämpas genom fysisk beröring. Studien diskuterar även urvalets begränsade storlek samt hur förväntanseffekter kan ha påverkat resultaten.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Syftet med denna studie är att fördjupa förståelsen för hur pedagoger uppfattar och vidareutvecklar arbetet med hållbar utveckling utifrån den kunskap och erfarenhet de har. Som teoretisk utgångspunkt används perspektiv på kunskap och hållbar utveckling, där även handlingskompetens utgör ett bärande begrepp. Studien genomförs med en kvalitativ ansats och bygger på semistrukturerade intervjuer med totalt sex pedagoger verksamma vid två förskolor i södra Sverige. Arbetet tar avstamp i två forskningsfrågor: (1) hur pedagoger relaterar till begreppet hållbar utveckling ur ett lärandeperspektiv samt (2) på vilket sätt normer och värderingar, när de framträder, kommer till uttryck i pedagogernas arbete med kunskapsbildning för hållbar utveckling. Resultaten visar att pedagogernas förståelse av hållbar utveckling främst knyts till de tre dimensionerna ekologisk, ekonomisk och social. Kunskapsbildningen i verksamheterna hämtar näring från fortbildningsinsatsen Grön flagg och/eller pedagogernas egna intressen.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "I den här studien har jag undersökt hur handledning tar form på arbetsplatser. Handledning är i dag ett begrepp som används allt oftare, men som samtidigt kan vara svårt att ringa in. Arbetets syfte är att belysa handledning och olika handledningsprocesser samt att pröva hur dessa skulle kunna tillämpas i arbetslivet, särskilt i samband med medarbetarsamtal. Jag avgränsar undersökningen till den del av medarbetarsamtalet som handlar om medarbetarens utveckling. Min teoretiska utgångspunkt är att handledande inslag kan förekomma i medarbetarsamtalet, men att hela samtalet inte nödvändigtvis kan beskrivas som handledning. För att undersöka detta har jag genomfört intervjuer med åtta personer på två olika arbetsplatser, där fyra var chefer och fyra var medarbetare, med fokus på deras erfarenheter av medarbetarsamtalet. Resultaten visar att ett handledande förhållningssätt tydligt kan urskiljas i medarbetarsamtalen på båda arbetsplatserna, och att metoder och perspektiv från handledningsfältet kan bidra till att vidareutveckla samtalens innehåll och kvalitet.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "I studien Samkönade äktenskap – ska Svenska kyrkan ha kvar vigselrätten eller inte genomförs en argumentationsanalys med hermeneutisk ansats och kvalitativ textanalys av debattartiklar som behandlar frågan om Svenska kyrkan bör behålla rätten att viga efter att staten gjort äktenskapslagen könsneutral. Materialet består av texter publicerade i Kyrkans tidning och Dagens Nyheter under perioden 2008-12-11 till 2009-10-31. Resultaten visar att förespråkare och motståndare i stor utsträckning lutar sig mot liknande argumentkategorier, men ger dem skilda betydelser genom olika perspektiv och tolkningar. Motståndarsidan betonar dock toleransargument i högre grad än förespråkarna. I ja-sidans resonemang kan dessutom en implicit kritik mot heteronormativa föreställningar urskiljas.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "I studien relateras styrdokumentens krav på undervisning om intersektionalitet till det innehåll som presenteras i religionskunskapsläroböcker för gymnasieskolan utgivna efter Gy 2011. Syftet var att undersöka om läroböckerna berör intersektionalitet explicit eller implicit och/eller om kategorier som kön, sexualitet, socioekonomiska villkor och etnicitet behandlas separat, samt i vilka sammanhang detta sker. Arbetet utgick från tre forskningsfrågor. Den första rörde hur religionsläroböcker publicerade från 2011 och framåt framställer relationen mellan världsreligionerna och nämnda kategorier. Den andra fokuserade på i vilka andra delar av böckerna (exempelvis kapitel) dessa kategorier tas upp. Den tredje behandlade vad läroböckerna förmedlar om själva begreppet och företeelsen intersektionalitet.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Denna uppsats undersöker Paulus förståelse av lagen, ett av de mest omstridda fälten inom paulusforskningen. Eftersom frågan om Paulus lagsyn är så avgörande för den bredare tolkningen av hans teologi menar många att den som vill förstå Paulus och hans brev måste ta ställning i ämnet. Forskningen är omfattande och debatten tycks fortfarande långt ifrån avgjord. Samtidigt kräver ämnet tydliga avgränsningar för att kunna behandlas inom ramen för en relativt kort studie. Därför avgränsar jag mig till en specifik textenhet i ett av Paulus brev där lagen står i centrum. Min frågeställning blir: Vad avser Paulus med begreppet 'lagen' i Rom 3:21–31?",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Denna studie behandlar teologiska tolkningar av två kungar i forntida Mesopotamien som gudomligförklarades: den gammalakkadiske härskaren Naram-Sin (ca 2254–2218 f.Kr.) och den nysumeriske kungen Shulgi (ca 2094–2047 f.Kr.). Perspektiven undersöks genom en induktivt upplagd historisk analys som tar sin utgångspunkt i hur ämnet har behandlats inom tidigare forskning. Då arbetet är utformat som en c-uppsats och därför inte kunnat baseras på primärmaterial, såsom arkeologiska fynd eller källtexter på originalspråk, bygger undersökningen uteslutande på sekundärlitteratur. Framställningen är uppdelad i tre avsnitt: två delar där respektive kung studeras var för sig och en avslutande del där resultaten ställs mot varandra i en jämförande analys. Resultaten visar att tolkningarna är mångfacetterade och ibland motsägelsefulla, samtidigt som både skillnader och beröringspunkter mellan kungarna framträder. Två motiv som ofta återkommer är fruktbarhet och himmelsanknytning.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Denna studie undersöker vilka attityder lärarstudenter och verksamma lärare har till skolavslutningar och högtidsfiranden som hålls i kyrkan, samt till motsvarande arrangemang där konfessionella inslag förekommer. Undersökningen bygger på en webbaserad enkät besvarad av både blivande och aktiva lärare. Resultaten visar att en majoritet i båda grupperna är positivt inställda till att använda kyrkorummet i samband med avslutningar och högtider. Däremot är den dominerande hållningen negativ när firandet innehåller konfessionella moment. Äldre deltagare, både bland verksamma lärare och lärarstudenter, uppvisar generellt en mer positiv inställning till såväl kyrkförläggning som konfessionella inslag jämfört med yngre. Studien drar slutsatsen att sekulariseringsprocessen i Sverige tycks fortgå i enlighet med reviderade sekulariseringsteorier, eftersom konfessionalitet i stor utsträckning inte uppfattas som önskvärd. Samtidigt framträder tydliga undantag från mönstret.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "En betydande del av den svenska bostadsstocken uppfördes under åren 1965–1974, då landet präglades av en omfattande bostadsbrist. Som svar fattade staten beslut om att bygga en miljon nya bostäder under perioden, det som kom att kallas miljonprogrammet. För att snabbt minska underskottet uppfördes bostäder i olika typer och storlekar, men områdena kom ofta att kännetecknas av storskalighet och ett tydligt upprepande av likartade byggnader. I dag står många av dessa hus inför ett stort renoveringsbehov. Samtidigt betraktas bebyggelsen som ett allmänintresse eftersom den representerar en viktig del av Sveriges arkitektur- och samhällshistoria, vilket innebär att kommunerna ofta ställer särskilda krav vid ombyggnationer. I Gävle har det kommunala bostadsbolaget Gavlegårdarna tagit initiativ till att vidareutveckla bygglovsprocessen för renovering i miljonprogramsområden. Syftet är att korta tiden fram till beviljat bygglov och att göra dialogen med kommunen mer effektiv genom hela projektet.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
];

// Thread-style Reddit-like discussions
// Each thread has a question and a list of comments
const THREADS = [
  {
    questionText: "Vad tycker ni om AI-genererade uppsatser i akademiska sammanhang?",
    comments: [
      {
        text: "Jag tycker det kan vara ett bra stöd, men studenten måste fortfarande stå för analysen.",
        isHuman: true,
      },
      {
        text: "Large language models enable unprecedented efficiency in knowledge production and assessment workflows.",
        isHuman: false,
      },
      {
        text: "Som handledare märker jag snabbt när en text inte låter som studenten själv.",
        isHuman: true,
      },
      {
        text: "It is empirically demonstrated that generative models always produce higher quality text than humans.",
        isHuman: false,
      },
    ],
  },
];

if (QUESTIONS.length === 0) {
  console.warn("QUESTIONS array is empty. Add at least one question in script.js.");
}

const MAX_QUESTIONS = 50;
if (QUESTIONS.length > MAX_QUESTIONS) {
  console.warn(`QUESTIONS has ${QUESTIONS.length} items, but only the first ${MAX_QUESTIONS} will be used.`);
}

const effectiveQuestions = QUESTIONS.slice(0, MAX_QUESTIONS);

// mode can be "intro", "reddit", "transition", "abstracts", "outro"
let mode = "intro";

let currentIndex = 0;
let hasAnsweredCurrent = false;
let numCorrect = 0;
let numAnswered = 0;

// State for reddit threads
let currentThreadIndex = 0;
let currentCommentIndex = 0;
let lastChoiceIsHuman = null;
let globalQuestionIndex = 0; // increments for every judgment (comment or abstract)
// Per-thread, per-comment answers: redditAnswers[threadIndex][commentIndex] = { choiceIsHuman }
let redditAnswers = [];
// When true, we're showing correct/incorrect for the current thread after user finished all comments
let redditShowingFeedback = false;


const RESULTS_ENDPOINT = "https://script.google.com/macros/s/AKfycbxAdn0Nk-FQVlgM8OyKfNw9HP7ugIv9xac50-duNwgcNLd6tlYN2VxY_NdwLiu0_gMb/exec";
const PARTICIPANT_ID = `${Date.now()}-${Math.floor(Math.random() * 1e6)}`;

const els = {
  questionLabel: document.getElementById("question-label"),
  questionTag: document.getElementById("question-tag"),
  questionTitle: document.getElementById("question-title"),
  questionText: document.getElementById("question-text"),
  commentsContainer: document.getElementById("comments-container"),
  controlsSection: document.querySelector(".controls"),
  subtitle: document.querySelector(".app-subtitle"),
  progressText: document.getElementById("progress-text"),
  progressBarInner: document.getElementById("progress-bar-inner"),
  btnHuman: document.getElementById("btn-human"),
  btnAi: document.getElementById("btn-ai"),
  btnPrev: document.getElementById("btn-prev"),
  btnExit: document.getElementById("btn-exit"),
  btnNext: document.getElementById("btn-next"),
  feedback: document.getElementById("feedback"),
  scoreCorrect: document.getElementById("score-correct"),
  scoreTotal: document.getElementById("score-total"),
};

const answers = new Array(effectiveQuestions.length).fill(null);

function computeTotalScoreSoFar() {
  const abstractAnswered = answers.filter(Boolean).length;
  const abstractCorrect = answers.reduce((acc, a, idx) => {
    if (!a) return acc;
    return acc + (a.choiceIsHuman === effectiveQuestions[idx].isHuman ? 1 : 0);
  }, 0);

  let commentAnswered = 0;
  let commentCorrect = 0;
  for (let t = 0; t < THREADS.length; t += 1) {
    const thread = THREADS[t];
    const threadAnswers = redditAnswers[t];
    if (!thread || !threadAnswers) continue;
    for (let c = 0; c < thread.comments.length; c += 1) {
      const ans = threadAnswers[c];
      if (!ans) continue;
      commentAnswered += 1;
      if (ans.choiceIsHuman === thread.comments[c].isHuman) {
        commentCorrect += 1;
      }
    }
  }

  return {
    answered: abstractAnswered + commentAnswered,
    correct: abstractCorrect + commentCorrect,
  };
}

function computeSectionScores() {
  const abstractAnswered = answers.filter(Boolean).length;
  const abstractCorrect = answers.reduce((acc, a, idx) => {
    if (!a) return acc;
    return acc + (a.choiceIsHuman === effectiveQuestions[idx].isHuman ? 1 : 0);
  }, 0);

  let commentAnswered = 0;
  let commentCorrect = 0;
  for (let t = 0; t < THREADS.length; t += 1) {
    const thread = THREADS[t];
    const threadAnswers = redditAnswers[t];
    if (!thread || !threadAnswers) continue;
    for (let c = 0; c < thread.comments.length; c += 1) {
      const ans = threadAnswers[c];
      if (!ans) continue;
      commentAnswered += 1;
      if (ans.choiceIsHuman === thread.comments[c].isHuman) {
        commentCorrect += 1;
      }
    }
  }

  return {
    comments: { answered: commentAnswered, correct: commentCorrect },
    abstracts: { answered: abstractAnswered, correct: abstractCorrect },
  };
}

async function sendAnswerEvent() {
  let q;
  let choiceIsHuman;
  let extra = {};
  let questionType = "";

  if (mode === "abstracts") {
    q = effectiveQuestions[currentIndex];
    const answer = answers[currentIndex];
    if (!q || !answer) return;
    choiceIsHuman = answer.choiceIsHuman;

    const isCorrect = choiceIsHuman === q.isHuman;

    const totals = computeTotalScoreSoFar();

    extra = {
      mode: "abstracts",
      isCorrect,
      totalCorrectSoFar: totals.correct,
      totalAnsweredSoFar: totals.answered,
    };
    questionType = "abstract";
  } else if (mode === "reddit") {
    const thread = THREADS[currentThreadIndex];
    const comment = thread && thread.comments[currentCommentIndex];
    const stored = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex];
    if (!thread || !comment || !stored) return;
    q = { text: comment.text, isHuman: comment.isHuman };
    choiceIsHuman = stored.choiceIsHuman;

    const isCorrect = choiceIsHuman === q.isHuman;
    const totals = computeTotalScoreSoFar();

    extra = {
      mode: "reddit",
      threadIndex: currentThreadIndex,
      commentIndex: currentCommentIndex,
      threadQuestionText: thread.questionText,
      isCorrect,
      totalCorrectSoFar: totals.correct,
      totalAnsweredSoFar: totals.answered,
    };
    questionType = "comment";
  } else {
    return;
  }

  const payload = {
    participantId: PARTICIPANT_ID,
    response: {
      questionIndex: globalQuestionIndex,
      questionType,
      questionText: q.text,
      isHumanLabel: q.isHuman,
      userGuessIsHuman: choiceIsHuman,
      ...extra,
    },
  };

  try {
    await fetch(RESULTS_ENDPOINT, {
      method: "POST",
      // mode: "no-cors",   // this is optional now; you can keep or remove it
      body: JSON.stringify(payload),
    });
  } catch (err) {
    console.error("Failed to send answer event", err);
  }
}

function hideChoices(hide) {
  if (!els.controlsSection) return;
  if (hide) els.controlsSection.classList.add("controls--no-choices");
  else els.controlsSection.classList.remove("controls--no-choices");
}

function clampIndex(index) {
  if (index < 0) return 0;
  if (index >= effectiveQuestions.length) return effectiveQuestions.length - 1;
  return index;
}

function renderIntro() {
  hideChoices(true);
  if (els.questionTitle) els.questionTitle.hidden = true;

  if (els.subtitle) {
    els.subtitle.textContent = "Du kan svara på så många frågor du vill, och du kan avsluta när som helst.";
  }

  els.questionLabel.textContent = "Välkommen!";
  els.questionTag.textContent = "Information";
  els.questionText.textContent =
    "Tack för att du deltar.\n\n" +
    "Upplägg:\n" +
    "1) Först får du bedöma kommentarer i en forumtråd (likt Reddit).\n" +
    "2) Därefter får du bedöma abstrakt från kandidatuppsatser.\n\n" +
    "För varje text ska du avgöra om den är skriven av en människa eller av en AI.\n\n" +
    "Ingen identifierande information om dig sparas i resultatet (t.ex. namn, e-post eller IP-adress).\n\n" +
    "Du kan när som helst klicka på \"Avsluta\" för att gå direkt till avslutningssidan.";

  if (els.commentsContainer) els.commentsContainer.innerHTML = "";

  els.progressText.textContent = "";
  els.progressBarInner.style.width = "0%";

  els.btnPrev.disabled = true;
  els.btnNext.disabled = false;
  els.btnNext.textContent = "Starta ▶";
}

function renderQuestion() {
  hideChoices(false);
  const q = effectiveQuestions[currentIndex];
  const total = effectiveQuestions.length;
  const questionNumber = currentIndex + 1;

  els.questionLabel.textContent = `Fråga ${questionNumber}`;
  if (els.questionTitle) {
    const title = q.title ? q.title.trim() : "";
    els.questionTitle.hidden = title.length === 0;
    els.questionTitle.textContent = title;
  }
  els.questionText.textContent = q.text;
  els.questionTag.textContent = q.type || "Item";

  els.progressText.textContent = `Fråga ${questionNumber} av ${total}`;
  const progressRatio = total > 0 ? questionNumber / total : 0;
  els.progressBarInner.style.width = `${Math.round(progressRatio * 100)}%`;

  els.btnPrev.disabled = currentIndex === 0;
  els.btnNext.disabled = !answers[currentIndex] && currentIndex !== total - 1;
  els.btnNext.textContent = currentIndex === total - 1 ? "Klara" : "Nästa ▶";

  resetChoiceStyles();
  applyAnswerStyles();
  renderFeedback();
  updateScoreSummary();
}

function renderThread() {
  const thread = THREADS[currentThreadIndex];
  if (!thread) return;
  hideChoices(false);
  if (els.questionTitle) els.questionTitle.hidden = true;

  if (!redditAnswers[currentThreadIndex]) {
    redditAnswers[currentThreadIndex] = thread.comments.map(() => null);
  }
  const threadAnswers = redditAnswers[currentThreadIndex];

  if (els.subtitle) {
    els.subtitle.textContent =
      "Läs kommentaren i tråden och avgör om den är skriven av en människa eller AI.";
  }

  els.questionLabel.textContent = `Tråd ${currentThreadIndex + 1}`;
  els.questionTag.textContent = "Kommentars-tråd";
  els.questionText.textContent = thread.questionText;

  if (els.commentsContainer) {
    els.commentsContainer.innerHTML = "";

    thread.comments.forEach((comment, idx) => {
      const row = document.createElement("div");
      let rowClass = "comment-row";
      if (redditShowingFeedback) {
        const ans = threadAnswers[idx];
        const isCorrect = ans && ans.choiceIsHuman === comment.isHuman;
        rowClass += isCorrect ? " comment-row--correct" : " comment-row--incorrect";
      } else if (idx === currentCommentIndex) {
        rowClass += " comment-row--active";
      }

      row.className = rowClass;

      const meta = document.createElement("div");
      meta.className = "comment-meta";
      meta.textContent = `Kommentar ${idx + 1}`;
      if (redditShowingFeedback && threadAnswers[idx]) {
        const ans = threadAnswers[idx];
        const isCorrect = ans.choiceIsHuman === comment.isHuman;
        const guess = ans.choiceIsHuman ? "Människa" : "AI";
        const actual = comment.isHuman ? "Människa" : "AI";
        meta.textContent += ` · Din bedömning: ${guess}. ${isCorrect ? "Rätt!" : "Rätt svar: " + actual + "."}`;
      }
      row.appendChild(meta);

      const body = document.createElement("div");
      body.className = "comment-body";
      body.textContent = comment.text;
      row.appendChild(body);
      els.commentsContainer.appendChild(row);
    });
  }

  const totalComments = thread.comments.length;
  const commentNumber = currentCommentIndex + 1;
  els.progressText.textContent = redditShowingFeedback
    ? `Resultat · Tråd ${currentThreadIndex + 1}`
    : `Kommentar ${commentNumber} av ${totalComments}`;
  const progressRatio = totalComments > 0 ? (redditShowingFeedback ? 1 : commentNumber / totalComments) : 0;
  els.progressBarInner.style.width = `${Math.round(progressRatio * 100)}%`;

  if (redditShowingFeedback) {
    els.btnPrev.disabled = true;
    els.btnNext.disabled = false;
    els.btnNext.textContent = currentThreadIndex === THREADS.length - 1 ? "Nästa del ▶" : "Nästa tråd ▶";
    resetChoiceStyles();
    els.feedback.textContent = "";
    els.feedback.classList.remove("correct", "incorrect");
    els.btnHuman.classList.add("disabled");
    els.btnAi.classList.add("disabled");
  } else {
    const currentAnswered = !!threadAnswers[currentCommentIndex];
    els.btnPrev.disabled = currentThreadIndex === 0 && currentCommentIndex === 0;
    els.btnNext.disabled = !currentAnswered;
    const isLastThread = currentThreadIndex === THREADS.length - 1;
    const isLastComment = commentNumber === totalComments;
    els.btnNext.textContent = isLastThread && isLastComment ? "Nästa del ▶" : "Nästa kommentar ▶";
    resetChoiceStyles();
    els.feedback.textContent = "";
    els.feedback.classList.remove("correct", "incorrect");
    if (currentAnswered) {
      const choice = threadAnswers[currentCommentIndex].choiceIsHuman;
      const btn = choice ? els.btnHuman : els.btnAi;
      btn.classList.add("selected", "disabled");
      (choice ? els.btnAi : els.btnHuman).classList.add("disabled");
    }
  }

  // Don't update the visible score while the user is still answering comments.
  // Update when we reveal the thread feedback (end of the thread).
  if (redditShowingFeedback) {
    updateScoreSummary();
  }
}

function renderTransition() {
  if (els.subtitle) {
    els.subtitle.textContent =
      "Nu börjar nästa del: bedöm uppsatsabstrakt. Läs noggrant och avgör om texten är skriven av en människa eller AI.";
  }
  if (els.questionTitle) els.questionTitle.hidden = true;

  els.questionLabel.textContent = "Nästa del";
  els.questionTag.textContent = "Instruktion";
  els.questionText.textContent =
    "Du har nu bedömt kommentarer i en diskussionstråd. I nästa del får du läsa uppsatsabstrakt ett i taget och avgöra om de är skrivna av en människa eller av en AI.";

  if (els.commentsContainer) {
    els.commentsContainer.innerHTML = "";
  }

  els.progressText.textContent = "";
  els.progressBarInner.style.width = "0%";

  resetChoiceStyles();
  els.feedback.textContent = "";
  els.feedback.classList.remove("correct", "incorrect");

  hideChoices(true);
  els.btnPrev.disabled = true;
  els.btnNext.disabled = false;
  els.btnNext.textContent = "Starta abstrakt-delen ▶";

  updateScoreSummary();
}

function renderOutro() {
  hideChoices(true);
  if (els.questionTitle) els.questionTitle.hidden = true;

  if (els.subtitle) {
    els.subtitle.textContent = "Tack för att du deltog!";
  }

  els.questionLabel.textContent = "Klart";
  els.questionTag.textContent = "Tack";
  const sections = computeSectionScores();
  const totals = computeTotalScoreSoFar();
  els.questionText.textContent =
    "Tack för att du har genomfört undersökningen.\n\n" +
    `Resultat (kommentarer): ${sections.comments.correct} / ${sections.comments.answered}\n` +
    `Resultat (abstrakt): ${sections.abstracts.correct} / ${sections.abstracts.answered}\n` +
    `Totalt: ${totals.correct} / ${totals.answered}\n\n` +
    "Om du vill kan du skriva en kort motivering/reflektion nedan (frivilligt).";

  if (els.commentsContainer) {
    els.commentsContainer.innerHTML = "";

    const box = document.createElement("div");
    box.className = "outro-box";

    const textarea = document.createElement("textarea");
    textarea.className = "outro-textarea";
    textarea.placeholder = "Skriv valfri motivering här...";
    textarea.rows = 5;

    const actions = document.createElement("div");
    actions.className = "outro-actions";

    const submit = document.createElement("button");
    submit.type = "button";
    submit.className = "nav-button primary";
    submit.textContent = "Skicka (frivilligt)";

    submit.addEventListener("click", async () => {
      const text = textarea.value.trim();
      if (!text) return;

      // Send as a separate row to the sheet
      globalQuestionIndex += 1;
      const payload = {
        participantId: PARTICIPANT_ID,
        response: {
          questionIndex: globalQuestionIndex,
          questionType: "reasoning",
          questionText: text,
          isHumanLabel: "",
          userGuessIsHuman: "",
          isCorrect: "",
          totalCorrectSoFar: totals.correct,
          totalAnsweredSoFar: totals.answered,
          mode: "outro",
        },
      };

      try {
        await fetch(RESULTS_ENDPOINT, { method: "POST", body: JSON.stringify(payload) });
        textarea.value = "";
        submit.textContent = "Skickat!";
        submit.disabled = true;
      } catch (err) {
        console.error("Failed to send reasoning", err);
      }
    });

    actions.appendChild(submit);
    box.appendChild(textarea);
    box.appendChild(actions);
    els.commentsContainer.appendChild(box);
  }

  els.progressText.textContent = "";
  els.progressBarInner.style.width = "0%";

  els.btnPrev.disabled = true;
  els.btnNext.disabled = false;
  els.btnNext.textContent = "Starta om ▶";

  updateScoreSummary();
}

function renderCurrent() {
  const shell = document.querySelector(".app-shell");
  if (shell) {
    shell.classList.toggle("theme-comments", mode === "reddit");
    shell.classList.toggle("theme-abstracts", mode === "abstracts");
  }
  if (mode === "intro") {
    renderIntro();
  } else if (mode === "reddit") {
    renderThread();
  } else if (mode === "transition") {
    renderTransition();
  } else if (mode === "outro") {
    renderOutro();
  } else {
    renderQuestion();
  }
}

function resetChoiceStyles() {
  [els.btnHuman, els.btnAi].forEach((btn) => {
    btn.classList.remove("selected-correct", "selected-incorrect", "disabled");
  });
}

function applyAnswerStyles() {
  const q = effectiveQuestions[currentIndex];
  const answer = answers[currentIndex];

  if (!answer) return;

  const isCorrect = answer.choiceIsHuman === q.isHuman;
  const selectedButton = answer.choiceIsHuman ? els.btnHuman : els.btnAi;

  selectedButton.classList.add(isCorrect ? "selected-correct" : "selected-incorrect");
  [els.btnHuman, els.btnAi].forEach((btn) => btn.classList.add("disabled"));
}

function renderFeedback() {
  const q = effectiveQuestions[currentIndex];
  const answer = answers[currentIndex];

  els.feedback.textContent = "";
  els.feedback.classList.remove("correct", "incorrect");

  if (!answer) {
    return;
  }

  const isCorrect = answer.choiceIsHuman === q.isHuman;
  if (isCorrect) {
    els.feedback.textContent = 'Du har rätt!';
    els.feedback.classList.add("correct");
  } else {
    const actualLabel = q.isHuman ? "skrivet av en människa" : "skrivet av en AI";
    els.feedback.textContent = `Inte korrekt. Det var ${actualLabel}.`;
    els.feedback.classList.add("incorrect");
  }
}

function updateScoreSummary() {
  const totals = computeTotalScoreSoFar();
  numAnswered = totals.answered;
  numCorrect = totals.correct;

  els.scoreCorrect.textContent = numCorrect.toString();
  els.scoreTotal.textContent = numAnswered.toString();
}

function recordAnswer(choiceIsHuman) {
  if (mode === "abstracts") {
    const existing = answers[currentIndex];
    if (existing) {
      existing.choiceIsHuman = choiceIsHuman;
    } else {
      answers[currentIndex] = { choiceIsHuman };
    }
    hasAnsweredCurrent = true;
    globalQuestionIndex += 1;
    sendAnswerEvent();
    renderCurrent();
    return;
  }
  if (mode === "reddit" && !redditShowingFeedback) {
    if (!redditAnswers[currentThreadIndex]) {
      redditAnswers[currentThreadIndex] = THREADS[currentThreadIndex].comments.map(() => null);
    }
    redditAnswers[currentThreadIndex][currentCommentIndex] = { choiceIsHuman };
    lastChoiceIsHuman = choiceIsHuman;
    globalQuestionIndex += 1;
    sendAnswerEvent();
    renderThread();
  }
}

function handleNext() {
  if (mode === "intro") {
    mode = "reddit";
    currentThreadIndex = 0;
    currentCommentIndex = 0;
    redditShowingFeedback = false;
    renderThread();
    return;
  }
  if (mode === "reddit") {
    const thread = THREADS[currentThreadIndex];
    const totalComments = thread.comments.length;

    if (redditShowingFeedback) {
      redditShowingFeedback = false;
      if (currentThreadIndex < THREADS.length - 1) {
        currentThreadIndex += 1;
        currentCommentIndex = 0;
        renderThread();
        return;
      }
      mode = "transition";
      renderTransition();
      return;
    }

    if (currentCommentIndex < totalComments - 1) {
      currentCommentIndex += 1;
      lastChoiceIsHuman = (redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex])
        ? redditAnswers[currentThreadIndex][currentCommentIndex].choiceIsHuman
        : null;
      renderThread();
      return;
    }

    // On last comment: show feedback for this thread
    const lastAnswered = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][totalComments - 1];
    if (lastAnswered) {
      redditShowingFeedback = true;
      renderThread();
      return;
    }

    if (currentThreadIndex < THREADS.length - 1) {
      currentThreadIndex += 1;
      currentCommentIndex = 0;
      renderThread();
      return;
    }

    mode = "transition";
    renderTransition();
    return;
  }

  if (mode === "transition") {
    // Start abstracts part
    mode = "abstracts";
    currentIndex = 0;
    hasAnsweredCurrent = !!answers[currentIndex];
    if (els.subtitle) {
      els.subtitle.textContent =
        "Läs abstraktet och avgör om det är skrivet av en människa eller AI.";
    }
    renderQuestion();
    return;
  }

  if (mode === "outro") {
    // restart
    mode = "intro";
    currentIndex = 0;
    currentThreadIndex = 0;
    currentCommentIndex = 0;
    hasAnsweredCurrent = false;
    numCorrect = 0;
    numAnswered = 0;
    globalQuestionIndex = 0;
    redditAnswers = [];
    redditShowingFeedback = false;
    lastChoiceIsHuman = null;
    renderCurrent();
    return;
  }

  const lastIndex = effectiveQuestions.length - 1;

  if (currentIndex === lastIndex) {
    const percent =
      answers.length === 0
        ? 0
        : Math.round(
            (numCorrect / Math.max(1, answers.filter(Boolean).length)) * 100
          );

    mode = "outro";
    renderOutro();
    return;
  }

  currentIndex = clampIndex(currentIndex + 1);
  hasAnsweredCurrent = !!answers[currentIndex];
  renderQuestion();
}

function handlePrev() {
  if (mode === "reddit" && !redditShowingFeedback) {
    if (currentThreadIndex === 0 && currentCommentIndex === 0) return;

    if (currentCommentIndex > 0) {
      currentCommentIndex -= 1;
      const prevAns = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex];
      lastChoiceIsHuman = prevAns ? prevAns.choiceIsHuman : null;
      renderThread();
      return;
    }

    if (currentThreadIndex > 0) {
      currentThreadIndex -= 1;
      const thread = THREADS[currentThreadIndex];
      currentCommentIndex = thread.comments.length - 1;
      const prevAns = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex];
      lastChoiceIsHuman = prevAns ? prevAns.choiceIsHuman : null;
      renderThread();
      return;
    }
  } else if (mode === "abstracts") {
    currentIndex = clampIndex(currentIndex - 1);
    hasAnsweredCurrent = !!answers[currentIndex];
    renderQuestion();
  }
}

function handleKeydown(event) {
  const target = event.target;
  const tagName = target && target.tagName ? target.tagName.toLowerCase() : "";
  const isTypingField =
    tagName === "textarea" ||
    tagName === "input" ||
    (target && target.isContentEditable);

  // Don't steal keystrokes while the user is typing
  if (isTypingField) return;

  if (event.key === "ArrowLeft") {
    event.preventDefault();
    if (!els.btnPrev.disabled) handlePrev();
  } else if (event.key === "ArrowRight") {
    event.preventDefault();
    if (!els.btnNext.disabled) handleNext();
  } else if (event.key.toLowerCase() === "h") {
    event.preventDefault();
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(true);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(true);
    }
  } else if (event.key.toLowerCase() === "a") {
    event.preventDefault();
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(false);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(false);
    }
  }
}

function init() {
  if (els.btnExit) {
    els.btnExit.addEventListener("click", () => {
      mode = "outro";
      renderOutro();
    });
  }
  if (!els.btnHuman || !els.btnAi) {
    console.error("Required DOM elements not found. Check index.html structure.");
    return;
  }

  els.btnHuman.addEventListener("click", () => {
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(true);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(true);
    }
  });

  els.btnAi.addEventListener("click", () => {
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(false);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(false);
    }
  });

  els.btnNext.addEventListener("click", handleNext);
  els.btnPrev.addEventListener("click", handlePrev);

  document.addEventListener("keydown", handleKeydown);

  renderCurrent();
}

window.addEventListener("DOMContentLoaded", init);
