"""make_embedding_auc_table_matched.py

Emit the document-matched version of tab:embedding-auc -- embedding CV ROC AUC
by generator x register x condition, every cell computed on the SAME 100
documents (the GPT-5.6 quiz100 subset) -- straight from the CSV, so the cells
cannot drift from a hand-transcription.

Source: 2_text_analysis_scripts/csv_files/embedding_auc_matched_gpt56subset.csv,
written by 2_text_analysis_scripts/scripts/matched_auc_control.py --permutations 1000.

Companion to make_embedding_auc_table.py, which emits the FULL-CORPUS table from
the embedding_twosample_*.csv files. The two are not interchangeable: the
full-corpus cells are measured at different n per generator (170/1,149 vs 100),
and a cross-validated AUC falls as n falls, so only the matched table supports
cross-generator comparison. See EMBEDDING_AUC_CAVEATS.md.

Writes embedding_auc_table_matched.tex next to this script and prints it.

Run: python src/3_ai_detection_scripts/make_embedding_auc_table_matched.py
"""
import os
from decimal import Decimal, ROUND_HALF_UP

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.dirname(HERE)
CSV = os.path.join(SRC, "2_text_analysis_scripts", "csv_files",
                   "embedding_auc_matched_gpt56subset.csv")
OUT = os.path.join(HERE, "embedding_auc_table_matched.tex")

CONDITIONS = [("baseline", "Baseline"),
              ("human_like", "Human-mimicking"),
              ("detector_evasive", "Detector-evasive")]
REGISTERS = [("formal", "Formal"), ("informal", "Informal")]
GENERATORS = ["GPT-5.2", "GPT-5.6", "Mistral 3.2"]


def r3(x):
    """3 dp, half-up (matches make_latex_tables.py / make_embedding_auc_table.py)."""
    return str(Decimal(str(float(x))).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP))


def fmt_p(p, n_perm):
    """A permutation p cannot resolve below (C+1)/(N+1) with C=0; print that as an
    inequality rather than a spuriously precise 0.001."""
    floor = 1.0 / (n_perm + 1)
    if p <= floor + 1e-12:
        return "$<$0.001"
    return r3(p)


def main():
    df = pd.read_csv(CSV)
    need = {"permutation_p_value", "ci95_lo", "ci95_hi", "n_permutations"}
    missing = need - set(df.columns)
    if missing:
        raise SystemExit(
            f"{os.path.basename(CSV)} lacks {sorted(missing)} -- it was written without "
            "significance tests. Re-run:\n  python src/2_text_analysis_scripts/scripts/"
            "matched_auc_control.py --permutations 1000")

    n_perm = int(df["n_permutations"].iloc[0])
    if df["n_permutations"].nunique() != 1:
        raise SystemExit("mixed n_permutations across cells; caption would be wrong")

    cells = {(r.generator, r.register, r.condition): r for r in df.itertuples()}

    blocks = []
    for gen in GENERATORS:
        reg_blocks = []
        for register, reg_label in REGISTERS:
            got = [cells.get((gen, register, c)) for c, _ in CONDITIONS]
            best = max((float(r.matched_cv_roc_auc) for r in got if r is not None),
                       default=None)
            lines = []
            for ci, ((cond, cond_label), r) in enumerate(zip(CONDITIONS, got)):
                if r is None:
                    auc = ci_txt = p_txt = "\\textit{pending}"
                else:
                    auc = r3(r.matched_cv_roc_auc)
                    if float(r.matched_cv_roc_auc) == best:
                        auc = f"\\textbf{{{auc}}}"
                    ci_txt = f"[{r3(r.ci95_lo)}, {r3(r.ci95_hi)}]"
                    p_txt = fmt_p(float(r.permutation_p_value), n_perm)
                lead = (f"      & \\multirow{{3}}{{*}}{{{reg_label}}}\n        "
                        if ci == 0 else "      & ")
                lines.append(f"{lead}& {cond_label:<16} & {auc} & {ci_txt} & {p_txt} \\\\")
            reg_blocks.append("\n".join(lines))
        blocks.append(f"    \\multirow{{6}}{{*}}{{{gen}}}\n"
                      + "\n    \\cmidrule(l){2-6}\n".join(reg_blocks))

    # n disclosure for the caption, straight from the data
    ns = sorted(set(int(r.n_per_class) for r in df.itertuples()))
    odd = sorted(set((r.generator, r.register, r.condition)
                     for r in df.itertuples() if int(r.n_per_class) != max(ns)))
    n_note = ""
    if odd:
        g, reg, cond = odd[0]
        n_lo = min(ns)
        n_note = (f" ($n={n_lo}$ for {g} {reg} {cond.replace('_', '-')}, "
                  "where two documents are missing)")

    table = (
        "% GENERATED by src/3_ai_detection_scripts/make_embedding_auc_table_matched.py\n"
        "% -- do not hand-edit. Re-run that script to refresh.\n"
        "% Source of truth: 2_text_analysis_scripts/csv_files/"
        "embedding_auc_matched_gpt56subset.csv\n"
        "% All cells computed on the SAME documents (the GPT-5.6 quiz100 subset), so\n"
        "% generators are comparable; the full-corpus figures are NOT, because a\n"
        "% cross-validated AUC falls as n falls. See EMBEDDING_AUC_CAVEATS.md.\n"
        "% Bold = most detectable prompt condition within each generator x register block.\n"
        "% REQUIRES: \\usepackage{booktabs}, \\usepackage{multirow}\n"
        "\\begin{table*}[h!]\n  \\centering\n  \\small\n"
        "  \\begin{tabular}{lllccc}\n    \\toprule\n"
        "    Generator & Register & Prompt & CV ROC AUC & 95\\% CI & Perm.\\ $p$ \\\\\n"
        "    \\midrule\n"
        + "\n    \\midrule\n".join(blocks)
        + "\n    \\bottomrule\n  \\end{tabular}\n"
        "  \\caption{Embedding-based classifier detectability for all LLM generators,\n"
        "  registers and prompt conditions. Cross-validated ROC AUC of a\n"
        "  logistic-regression two-sample test on multilingual sentence embeddings\n"
        "  (\\texttt{paraphrase-multilingual-mpnet-base-v2}, 5-fold CV). AUC${}=0.5$ is\n"
        "  chance; higher means more separable from human text. Every cell is computed on\n"
        f"  the same {max(ns)} documents per class --- the subset for which all three generators\n"
        f"  produced text --- so the generators are directly comparable{n_note}.\n"
        "  This matters: the statistic is a \\emph{cross-validated} AUC, so it falls as $n$\n"
        "  falls, and comparing generators measured at different $n$ understates the one\n"
        "  measured on fewer documents. Bold marks the most detectable prompt condition\n"
        "  within each generator and register.\n"
        f"  $p$ is a label-permutation test ({n_perm:,} permutations); its attainable floor is\n"
        f"  $1/({n_perm:,}+1)$, so \\mbox{{$<$0.001}} means no permutation reached the observed\n"
        "  AUC and is not a point estimate. All cells reject the null of no separability,\n"
        "  but the two GPT-5.2 formal cells at $p=0.003$ and $p=0.005$ do so an order of\n"
        "  magnitude less decisively than the rest. Intervals are Hanley--McNeil\n"
        "  normal approximations, indicative of relative precision rather than exact\n"
        "  inference, since the point estimate is itself cross-validated.}\n"
        "  \\label{tab:embedding-auc}\n\\end{table*}\n"
    )

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(table)
    print(table)
    print(f"wrote {os.path.relpath(OUT, SRC)}")


if __name__ == "__main__":
    main()
