"""Build a human-vs-LLM detection quiz that mixes the three prompt conditions equally.

Texts are copied VERBATIM from sv_abstracts_adversarial.csv (read straight from the CSV
cells — no editing, no rephrasing). Each quiz item is a distinct thesis, so no thesis
appears twice and a human item is never the twin of an LLM item.

Composition (edit the constants to resize):
  N_HUMAN human abstracts (column 'Abstract')
  N_PER_COND LLM abstracts from EACH of baseline / human_like / detector_aware
Default = 6 human + 2+2+2 LLM = 12 items (a comfortable length for a human taker).

Outputs (into this folder):
  mixed_quiz.csv        full data + answer key (order, title, text, is_human, condition, source_row)
  mixed_quiz_human.md   human-facing quiz: numbered title+text, no answers, key hidden at the bottom
"""
import os
import random

import pandas as pd

N_HUMAN = 6
N_PER_COND = 2
MAX_WORDS = 350  # skip abstracts longer than this (keeps items readable)
SEED = 42  # fixed for a reproducible quiz

_here = os.path.dirname(os.path.abspath(__file__))
_src = os.path.dirname(_here)
IN_CSV = os.path.join(_src, "1_data_collection", "llm_abstracts", "abstracts", "sv_abstracts_adversarial.csv")
OUT_CSV = os.path.join(_here, "mixed_quiz.csv")
OUT_MD = os.path.join(_here, "mixed_quiz_human.md")

# condition -> source column in the CSV (text copied exactly from these cells)
COND_COL = {
    "human": "Abstract",
    "baseline": "Abstract_baseline",
    "human_like": "Abstract_human_like",
    "detector_aware": "Abstract_detector_aware",
}


def main():
    df = pd.read_csv(IN_CSV, encoding="utf-8")
    rng = random.Random(SEED)

    # one role per distinct thesis row
    roles = ["human"] * N_HUMAN + sum(([c] * N_PER_COND for c in ("baseline", "human_like", "detector_aware")), [])
    n_items = len(roles)

    # Assign each role a distinct row whose text for that role is within the word
    # limit, so no abstract shown in the quiz exceeds MAX_WORDS.
    used = set()
    rows = []
    for cond in roles:
        eligible = [i for i in range(len(df))
                    if i not in used
                    and len(str(df.iloc[i][COND_COL[cond]]).split()) <= MAX_WORDS]
        row_idx = rng.choice(eligible)
        used.add(row_idx)
        rows.append(row_idx)

    items = []
    for row_idx, cond in zip(rows, roles):
        r = df.iloc[row_idx]
        items.append({
            "title": str(r["Title"]),          # verbatim
            "text": str(r[COND_COL[cond]]),     # verbatim
            "is_human": cond == "human",
            "condition": cond,
            "source_row": int(row_idx),
        })

    rng.shuffle(items)  # so conditions/human aren't grouped

    # ---- full data + answer key ----
    out = pd.DataFrame(
        [{"order": i + 1, **it} for i, it in enumerate(items)],
        columns=["order", "title", "text", "is_human", "condition", "source_row"],
    )
    out.to_csv(OUT_CSV, index=False, encoding="utf-8")

    # ---- human-facing quiz (no answers up top) ----
    lines = [
        "# Human vs AI abstract quiz",
        "",
        f"{n_items} Swedish bachelor-thesis abstracts. For each one, decide whether the "
        "**abstract text** was written by a **human** or **generated by an AI**. "
        "(The title is always the real thesis title; judge the abstract only.)",
        "",
        "---",
        "",
    ]
    for i, it in enumerate(items, 1):
        lines += [f"## {i}. {it['title']}", "", it["text"], "", "**Human or AI?** ______", "", "---", ""]

    lines += [
        "",
        "<!-- ================= ANSWER KEY (do not read until done) ================= -->",
        "",
        "## Answer key",
        "",
        "| # | Answer | Condition |",
        "|---|--------|-----------|",
    ]
    for i, it in enumerate(items, 1):
        ans = "Human" if it["is_human"] else "AI"
        lines.append(f"| {i} | {ans} | {it['condition']} |")

    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    n_llm = n_items - N_HUMAN
    print(f"Wrote {n_items} items ({N_HUMAN} human + {n_llm} LLM: {N_PER_COND} each of baseline/human_like/detector_aware)")
    print(f"  {OUT_CSV}")
    print(f"  {OUT_MD}")


if __name__ == "__main__":
    main()
